import ExcelJS from"exceljs";
import{saveAs}from"file-saver";

const money=(value)=>Number(value||0);
const num=(value)=>Number(value||0);

const COLORS={
dark:"0A0D17",
darkSoft:"1F2937",
gold:"D4B483",
goldSoft:"F4EBDD",
white:"FFFFFF",
black:"111111",
gray:"6B7280",
lightGray:"F7F7F4",
softFill:"FAFAF8",
border:"D9D9D2",
redFill:"FDE8E7",
redText:"B42318",
orangeFill:"FFF1E6",
orangeText:"C2410C",
greenFill:"E8F5E9",
greenText:"1B5E20"
};

const FONT_NAME="Arial";

const thinBorder={
top:{style:"thin",color:{argb:COLORS.border}},
left:{style:"thin",color:{argb:COLORS.border}},
bottom:{style:"thin",color:{argb:COLORS.border}},
right:{style:"thin",color:{argb:COLORS.border}}
};

const formatRangeLabel=(value)=>{
const labels={
today:"Today",
week:"This Week",
month:"This Month",
year:"This Year"
};
return labels[value]||String(value||"All");
};

const formatBranchLabel=(value)=>{
if(!value||String(value).toLowerCase()==="all")return"All Branches";
return String(value);
};

const getExportedBy=()=>{
return localStorage.getItem("adminName")||
localStorage.getItem("name")||
"Saint Clothing Admin";
};

const getGeneratedDate=()=>{
return new Date().toLocaleString("en-PH",{
year:"numeric",
month:"long",
day:"numeric",
hour:"numeric",
minute:"2-digit",
hour12:true
});
};

const sanitizeFileName=(value)=>{
return String(value||"all")
.trim()
.toLowerCase()
.replace(/[^a-z0-9]+/g,"-")
.replace(/^-+|-+$/g,"")||"all";
};

const columnNumberToName=(num)=>{
let name="";
while(num>0){
const remainder=(num-1)%26;
name=String.fromCharCode(65+remainder)+name;
num=Math.floor((num-1)/26);
}
return name;
};

const buildWorkbook=()=>{
const workbook=new ExcelJS.Workbook();

workbook.creator="Saint Clothing Admin";
workbook.lastModifiedBy=getExportedBy();
workbook.created=new Date();
workbook.modified=new Date();
workbook.company="Saint Clothing";
workbook.subject="Saint Clothing Dashboard Report";
workbook.title="Saint Clothing Dashboard Report";
workbook.description="Administrative dashboard report generated by Saint Clothing.";

return workbook;
};

const saveWorkbook=async(workbook,fileName)=>{
const buffer=await workbook.xlsx.writeBuffer();

const blob=new Blob([buffer],{
type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
});

saveAs(blob,fileName);
};

const applyBaseFont=(worksheet)=>{
worksheet.eachRow({includeEmpty:true},(row)=>{
row.eachCell({includeEmpty:true},(cell)=>{
cell.font={
...cell.font,
name:FONT_NAME
};
});
});
};

const applyBorder=(cell)=>{
cell.border=thinBorder;
};

const styleReportTitle=(cell)=>{
cell.font={
name:FONT_NAME,
bold:true,
size:20,
color:{argb:COLORS.white}
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.dark}
};

cell.alignment={
horizontal:"center",
vertical:"middle"
};
};

const styleReportSubtitle=(cell)=>{
cell.font={
name:FONT_NAME,
bold:true,
size:10,
color:{argb:COLORS.gold}
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.dark}
};

cell.alignment={
horizontal:"center",
vertical:"middle"
};
};

const styleMetaLabel=(cell)=>{
cell.font={
name:FONT_NAME,
bold:true,
size:10,
color:{argb:COLORS.dark}
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.goldSoft}
};

cell.alignment={
horizontal:"left",
vertical:"middle"
};

applyBorder(cell);
};

const styleMetaValue=(cell)=>{
cell.font={
name:FONT_NAME,
size:10,
color:{argb:COLORS.black}
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.white}
};

cell.alignment={
horizontal:"left",
vertical:"middle",
wrapText:true
};

applyBorder(cell);
};

const styleSectionTitle=(cell)=>{
cell.font={
name:FONT_NAME,
bold:true,
size:11,
color:{argb:COLORS.white}
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.dark}
};

cell.alignment={
horizontal:"left",
vertical:"middle"
};

applyBorder(cell);
};

const styleHeaderCell=(cell)=>{
cell.font={
name:FONT_NAME,
bold:true,
size:10,
color:{argb:COLORS.white}
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.dark}
};

cell.alignment={
horizontal:"center",
vertical:"middle",
wrapText:true
};

applyBorder(cell);
};

const addReportHeader=({
worksheet,
title,
subtitle,
endCol,
branchLabel="All Branches",
rangeLabel="All",
generatedAt=getGeneratedDate(),
exportedBy=getExportedBy()
})=>{
worksheet.mergeCells(1,1,1,endCol);

const titleCell=worksheet.getCell(1,1);
titleCell.value=title;
styleReportTitle(titleCell);
worksheet.getRow(1).height=30;

worksheet.mergeCells(2,1,2,endCol);

const subtitleCell=worksheet.getCell(2,1);
subtitleCell.value=subtitle;
styleReportSubtitle(subtitleCell);
worksheet.getRow(2).height=21;

const valueEndCol=Math.max(2,endCol);

worksheet.getCell(4,1).value="Branch";
styleMetaLabel(worksheet.getCell(4,1));

if(valueEndCol>=2){
worksheet.mergeCells(4,2,4,valueEndCol);
}

worksheet.getCell(4,2).value=formatBranchLabel(branchLabel);
styleMetaValue(worksheet.getCell(4,2));

worksheet.getCell(5,1).value="Range";
styleMetaLabel(worksheet.getCell(5,1));

if(valueEndCol>=2){
worksheet.mergeCells(5,2,5,valueEndCol);
}

worksheet.getCell(5,2).value=rangeLabel;
styleMetaValue(worksheet.getCell(5,2));

worksheet.getCell(6,1).value="Generated";
styleMetaLabel(worksheet.getCell(6,1));

if(valueEndCol>=2){
worksheet.mergeCells(6,2,6,valueEndCol);
}

worksheet.getCell(6,2).value=generatedAt;
styleMetaValue(worksheet.getCell(6,2));

worksheet.getCell(7,1).value="Exported By";
styleMetaLabel(worksheet.getCell(7,1));

if(valueEndCol>=2){
worksheet.mergeCells(7,2,7,valueEndCol);
}

worksheet.getCell(7,2).value=exportedBy;
styleMetaValue(worksheet.getCell(7,2));

worksheet.getRow(4).height=20;
worksheet.getRow(5).height=20;
worksheet.getRow(6).height=20;
worksheet.getRow(7).height=20;
};

const addSectionTitle=(worksheet,row,startCol,endCol,title)=>{
worksheet.mergeCells(row,startCol,row,endCol);

const cell=worksheet.getCell(row,startCol);
cell.value=title;
styleSectionTitle(cell);
worksheet.getRow(row).height=22;
};

const styleBodyCells=({
worksheet,
startRow,
endRow,
startCol,
totalCols,
numericColumns=[],
currencyColumns=[],
lowStockColumn=null,
statusColumn=null
})=>{
for(let rowIndex=startRow;rowIndex<=endRow;rowIndex++){
const alternate=(rowIndex-startRow)%2===1;

for(let index=0;index<totalCols;index++){
const absoluteCol=startCol+index;
const localCol=index+1;
const cell=worksheet.getCell(rowIndex,absoluteCol);

cell.font={
name:FONT_NAME,
size:10,
color:{argb:COLORS.black}
};

cell.alignment={
vertical:"middle",
horizontal:numericColumns.includes(localCol)||currencyColumns.includes(localCol)?"right":"left",
wrapText:true
};

cell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:alternate?COLORS.softFill:COLORS.white}
};

applyBorder(cell);
}

if(lowStockColumn){
const stockCell=worksheet.getCell(
rowIndex,
startCol+lowStockColumn-1
);

const stockValue=Number(stockCell.value);

if(Number.isFinite(stockValue)){
if(stockValue<=2){
stockCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.redFill}
};

stockCell.font={
name:FONT_NAME,
bold:true,
color:{argb:COLORS.redText}
};
}else if(stockValue<=5){
stockCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.orangeFill}
};

stockCell.font={
name:FONT_NAME,
bold:true,
color:{argb:COLORS.orangeText}
};
}
}
}

if(statusColumn){
const statusCell=worksheet.getCell(
rowIndex,
startCol+statusColumn-1
);

const status=String(statusCell.value||"").trim().toLowerCase();

if(
status.includes("delivered")||
status.includes("completed")||
status.includes("paid")
){
statusCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.greenFill}
};

statusCell.font={
name:FONT_NAME,
bold:true,
color:{argb:COLORS.greenText}
};
}else if(
status.includes("pending")||
status.includes("processing")||
status.includes("packing")||
status.includes("order placed")
){
statusCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.orangeFill}
};

statusCell.font={
name:FONT_NAME,
bold:true,
color:{argb:COLORS.orangeText}
};
}else if(
status.includes("cancelled")||
status.includes("canceled")||
status.includes("failed")||
status.includes("rejected")
){
statusCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.redFill}
};

statusCell.font={
name:FONT_NAME,
bold:true,
color:{argb:COLORS.redText}
};
}
}
}
};

const addDataTable=({
worksheet,
startRow,
startCol,
title,
headers,
rows,
numericColumns=[],
currencyColumns=[],
lowStockColumn=null,
statusColumn=null,
addFilter=true
})=>{
const safeRows=rows?.length
?rows
:[headers.map((_,index)=>index===0?"No data available":"")];

const totalCols=headers.length;
const endCol=startCol+totalCols-1;

addSectionTitle(
worksheet,
startRow,
startCol,
endCol,
title
);

const headerRowNumber=startRow+1;
const headerRow=worksheet.getRow(headerRowNumber);

headers.forEach((header,index)=>{
const cell=worksheet.getCell(
headerRowNumber,
startCol+index
);

cell.value=header;
styleHeaderCell(cell);
});

headerRow.height=24;

safeRows.forEach((row,rowIndex)=>{
row.forEach((value,colIndex)=>{
worksheet.getCell(
headerRowNumber+1+rowIndex,
startCol+colIndex
).value=value;
});
});

const bodyStart=headerRowNumber+1;
const bodyEnd=headerRowNumber+safeRows.length;

styleBodyCells({
worksheet,
startRow:bodyStart,
endRow:bodyEnd,
startCol,
totalCols,
numericColumns,
currencyColumns,
lowStockColumn,
statusColumn
});

currencyColumns.forEach((localCol)=>{
for(let row=bodyStart;row<=bodyEnd;row++){
worksheet.getCell(
row,
startCol+localCol-1
).numFmt='"₱"#,##0.00';
}
});

numericColumns.forEach((localCol)=>{
if(currencyColumns.includes(localCol))return;

for(let row=bodyStart;row<=bodyEnd;row++){
worksheet.getCell(
row,
startCol+localCol-1
).numFmt="#,##0";
}
});

if(addFilter){
worksheet.autoFilter={
from:{
row:headerRowNumber,
column:startCol
},
to:{
row:headerRowNumber,
column:endCol
}
};
}

return{
headerRow:headerRowNumber,
bodyStart,
bodyEnd,
endCol
};
};

const addSummaryCards=({
worksheet,
startRow,
stats,
endCol=8
})=>{
addSectionTitle(
worksheet,
startRow,
1,
endCol,
"DASHBOARD SUMMARY"
);

const cards=[
["Total Revenue",money(stats.totalRevenue),true],
["Total Orders",num(stats.totalOrders),false],
["Total Products",num(stats.totalProducts),false],
["Total Users",num(stats.totalUsers),false],
["Net Profit",money(stats.netProfit),true],
["Profit Margin",`${num(stats.netProfitMargin)}%`,false],
["Low Stock",num(stats.lowStockCount),false]
];

let row=startRow+1;

cards.forEach(([label,value,isCurrency],index)=>{
const left=index%2===0;
const col=left?1:5;

if(index>0&&left)row++;

worksheet.mergeCells(row,col,row,col+1);
worksheet.mergeCells(row,col+2,row,col+3);

const labelCell=worksheet.getCell(row,col);
const valueCell=worksheet.getCell(row,col+2);

labelCell.value=label;
valueCell.value=value;

labelCell.font={
name:FONT_NAME,
bold:true,
size:10,
color:{argb:COLORS.dark}
};

labelCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.goldSoft}
};

labelCell.alignment={
horizontal:"left",
vertical:"middle"
};

valueCell.font={
name:FONT_NAME,
bold:true,
size:11,
color:{argb:COLORS.dark}
};

valueCell.fill={
type:"pattern",
pattern:"solid",
fgColor:{argb:COLORS.white}
};

valueCell.alignment={
horizontal:"right",
vertical:"middle"
};

labelCell.border=thinBorder;
valueCell.border=thinBorder;

if(isCurrency){
valueCell.numFmt='"₱"#,##0.00';
}

worksheet.getRow(row).height=23;
});

return row;
};

const autoFitColumns=(worksheet,min=10,max=32)=>{
worksheet.columns.forEach((column)=>{
let maxLength=min;

column.eachCell({includeEmpty:true},(cell)=>{
let value="";

if(cell.value===null||cell.value===undefined){
value="";
}else if(typeof cell.value==="object"){
value=cell.text||"";
}else{
value=String(cell.value);
}

maxLength=Math.max(
maxLength,
Math.min(value.length+2,max)
);
});

column.width=Math.min(
Math.max(column.width||0,maxLength),
max
);
});
};

const configureWorksheet=({
worksheet,
lastRow,
lastCol
})=>{
worksheet.views=[
{
state:"normal"
}
];

worksheet.pageSetup={
orientation:"landscape",
paperSize:9,
fitToPage:true,
fitToWidth:1,
fitToHeight:0,
horizontalCentered:true,
margins:{
left:0.25,
right:0.25,
top:0.5,
bottom:0.5,
header:0.2,
footer:0.3
},
printArea:`A1:${columnNumberToName(lastCol)}${lastRow}`
};

worksheet.headerFooter={
oddHeader:"&C&BSAINT CLOTHING",
evenHeader:"&C&BSAINT CLOTHING",
oddFooter:"&LSaint Clothing Dashboard Report&CConfidential&RPage &P of &N",
evenFooter:"&LSaint Clothing Dashboard Report&CConfidential&RPage &P of &N"
};

worksheet.properties.defaultRowHeight=18;

applyBaseFont(worksheet);
};

const getDashboardBranchLabel=({
role,
branch,
selectedBranch
})=>{
if(role==="admin"){
return formatBranchLabel(selectedBranch);
}

return formatBranchLabel(branch);
};

const getOverallRangeLabel=({
overviewRange,
weeklyChartRange,
monthlyChartRange,
categoryRange,
topProductsRange,
lowStockRange,
recentOrdersRange
})=>{
return[
`Overview: ${formatRangeLabel(overviewRange)}`,
`Sales Trend: ${formatRangeLabel(weeklyChartRange)}`,
`Revenue & Profit: ${formatRangeLabel(monthlyChartRange)}`,
`Categories: ${formatRangeLabel(categoryRange)}`,
`Top Products: ${formatRangeLabel(topProductsRange)}`,
`Low Stock: ${formatRangeLabel(lowStockRange)}`,
`Recent Orders: ${formatRangeLabel(recentOrdersRange)}`
].join(" | ");
};

export const exportDashboardWorkbook=async({
role,
branch,
selectedBranch,
overviewRange,
weeklyChartRange,
monthlyChartRange,
categoryRange,
topProductsRange,
lowStockRange,
recentOrdersRange,
stats,
weeklySales,
monthlySales,
categorySales,
topProducts,
lowStockProducts,
recentOrders
})=>{
const workbook=buildWorkbook();

const branchLabel=getDashboardBranchLabel({
role,
branch,
selectedBranch
});

const rangeLabel=getOverallRangeLabel({
overviewRange,
weeklyChartRange,
monthlyChartRange,
categoryRange,
topProductsRange,
lowStockRange,
recentOrdersRange
});

const sheet=workbook.addWorksheet("Dashboard Report",{
properties:{
tabColor:{argb:COLORS.gold}
}
});

const lastCol=8;

addReportHeader({
worksheet:sheet,
title:"SAINT CLOTHING DASHBOARD REPORT",
subtitle:"Administrative Performance, Sales and Inventory Overview",
endCol:lastCol,
branchLabel,
rangeLabel
});

let currentRow=9;

currentRow=addSummaryCards({
worksheet:sheet,
startRow:currentRow,
stats,
endCol:lastCol
})+2;

const topResult=addDataTable({
worksheet:sheet,
startRow:currentRow,
startCol:1,
title:`TOP PRODUCTS • ${formatRangeLabel(topProductsRange)}`,
headers:[
"Product",
"Units Sold",
"Revenue"
],
rows:topProducts?.length
?topProducts.map((item)=>[
item.name,
num(item.sold),
money(item.revenue)
])
:[],
numericColumns:[2],
currencyColumns:[3],
addFilter:false
});

currentRow=topResult.bodyEnd+2;

const categoryResult=addDataTable({
worksheet:sheet,
startRow:currentRow,
startCol:1,
title:`CATEGORY PERFORMANCE • ${formatRangeLabel(categoryRange)}`,
headers:[
"Category",
"Units Sold"
],
rows:categorySales?.labels?.length
?categorySales.labels.map((label,index)=>[
label,
num(categorySales.data?.[index]||0)
])
:[],
numericColumns:[2],
addFilter:false
});

currentRow=categoryResult.bodyEnd+2;

const salesResult=addDataTable({
worksheet:sheet,
startRow:currentRow,
startCol:1,
title:`SALES TREND • ${formatRangeLabel(weeklyChartRange)}`,
headers:[
"Period",
"Sales"
],
rows:weeklySales?.labels?.length
?weeklySales.labels.map((label,index)=>[
label,
money(weeklySales.data?.[index]||0)
])
:[],
currencyColumns:[2],
addFilter:false
});

currentRow=salesResult.bodyEnd+2;

const revenueResult=addDataTable({
worksheet:sheet,
startRow:currentRow,
startCol:1,
title:`REVENUE AND PROFIT • ${formatRangeLabel(monthlyChartRange)}`,
headers:[
"Period",
"Revenue",
"Profit"
],
rows:monthlySales?.labels?.length
?monthlySales.labels.map((label,index)=>[
label,
money(monthlySales.revenue?.[index]||0),
money(monthlySales.netProfit?.[index]||0)
])
:[],
currencyColumns:[2,3],
addFilter:false
});

currentRow=revenueResult.bodyEnd+2;

const lowStockResult=addDataTable({
worksheet:sheet,
startRow:currentRow,
startCol:1,
title:"LOW STOCK ALERT",
headers:[
"Product",
"Category",
"Branch",
"Stock Left",
"Price"
],
rows:lowStockProducts?.length
?lowStockProducts.map((item)=>[
item.name,
item.category,
item.branch,
num(item.stock),
money(item.price)
])
:[],
numericColumns:[4],
currencyColumns:[5],
lowStockColumn:4,
addFilter:false
});

currentRow=lowStockResult.bodyEnd+2;

const ordersResult=addDataTable({
worksheet:sheet,
startRow:currentRow,
startCol:1,
title:`RECENT ORDERS • ${formatRangeLabel(recentOrdersRange)}`,
headers:[
"Order ID",
"Customer",
"Amount",
"Status",
"Payment Method",
"Date"
],
rows:recentOrders?.length
?recentOrders.map((order)=>[
order._id,
`${order.address?.firstName||""} ${order.address?.lastName||""}`.trim()||"Customer",
money(order.amount),
order.status||"Pending",
order.paymentMethod||"COD",
new Date(order.date||order.createdAt).toLocaleString("en-PH")
])
:[],
currencyColumns:[3],
statusColumn:4,
addFilter:true
});

const lastRow=ordersResult.bodyEnd;

autoFitColumns(sheet);

sheet.getColumn(1).width=Math.max(sheet.getColumn(1).width||0,24);
sheet.getColumn(2).width=Math.max(sheet.getColumn(2).width||0,16);
sheet.getColumn(3).width=Math.max(sheet.getColumn(3).width||0,16);
sheet.getColumn(4).width=Math.max(sheet.getColumn(4).width||0,16);
sheet.getColumn(5).width=Math.max(sheet.getColumn(5).width||0,18);
sheet.getColumn(6).width=Math.max(sheet.getColumn(6).width||0,22);

configureWorksheet({
worksheet:sheet,
lastRow,
lastCol
});

const date=new Date().toISOString().slice(0,10);

await saveWorkbook(
workbook,
`saint_dashboard_${sanitizeFileName(branchLabel)}_${date}.xlsx`
);
};

export const exportSingleDashboardSection=async({
sheetTitle,
fileName,
subtitle,
headers,
rows,
currencyColumns=[],
numberColumns=[],
lowStockColumn=null,
statusColumn=null
})=>{
const workbook=buildWorkbook();

const safeSheetTitle=String(sheetTitle||"Dashboard")
.replace(/[\\/*?:[\]]/g,"")
.slice(0,31)||"Dashboard";

const sheet=workbook.addWorksheet(safeSheetTitle,{
properties:{
tabColor:{argb:COLORS.gold}
}
});

const endCol=Math.max(headers.length,2);

const role=localStorage.getItem("role")||"";
const branch=localStorage.getItem("branch")||"";
const storedSelectedBranch=localStorage.getItem("selectedBranch")||"";

const branchLabel=role==="admin"
?storedSelectedBranch&&storedSelectedBranch!=="all"
?storedSelectedBranch
:"All Branches"
:branch||"All Branches";

addReportHeader({
worksheet:sheet,
title:`SAINT CLOTHING ${String(sheetTitle||"DASHBOARD").toUpperCase()} REPORT`,
subtitle:subtitle||"Saint Clothing Dashboard Export",
endCol,
branchLabel,
rangeLabel:subtitle||"Dashboard section"
});

const tableResult=addDataTable({
worksheet:sheet,
startRow:9,
startCol:1,
title:String(sheetTitle||"Dashboard").toUpperCase(),
headers,
rows,
numericColumns:numberColumns,
currencyColumns,
lowStockColumn,
statusColumn,
addFilter:true
});

autoFitColumns(sheet);

headers.forEach((header,index)=>{
const headerText=String(header||"").toLowerCase();
const column=sheet.getColumn(index+1);

if(
headerText.includes("product")||
headerText.includes("customer")
){
column.width=Math.max(column.width||0,24);
}

if(
headerText.includes("order id")||
headerText.includes("date")
){
column.width=Math.max(column.width||0,20);
}

if(headerText.includes("payment method")){
column.width=Math.max(column.width||0,18);
}
});

configureWorksheet({
worksheet:sheet,
lastRow:tableResult.bodyEnd,
lastCol:endCol
});

await saveWorkbook(
workbook,
fileName
);
};